apiVersion: ENC[AES256_GCM,data:aus=,iv:AXZS5v+0Ceu1m3ZR3c/BaMpdha2RR0Gx+LoZDaJHDOk=,tag:/NbIE2N/+Lnrs5NLF1AUCg==,type:str]
kind: ENC[AES256_GCM,data:7IM95fz1,iv:Trd9abOjBggKw9LMCveFAAILiNWhKOPmrUdBHsJsY+A=,tag:2WI7qqRK5AgW7R/PyvAbcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JeHuLXoQs5/i25RjalNlu5o=,iv:DDZqRF0VkDceaGBIk79JW7YG4Tc4rfL7tTA+TjqJeD8=,tag:LB+O8E5UJ53IeKnrBQU2+w==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:rpUeYMVF7wW4+A==,iv:xaBhpLGvGXddtGtNO1vAQMrwD8gz0O3XFlsXEZUYDhU=,tag:PZd5Jeg2VitpJWjUfG+lMw==,type:str]
type: ENC[AES256_GCM,data:ANAdLW4b,iv:BlT4Fn3pY7TBoOk4KUsqmtbfcVJX6MBwOC4UEmVjvLA=,tag:GNAE9Ea8E6i0Ggtnbq6yrg==,type:str]
stringData:
    DEMO_API_KEY: ENC[AES256_GCM,data:HU22O5M4ZEvqtbXh8YyCtolzVaF4ywQiFn0JK4VBAxU=,iv:xHr/z0ajBrpDkPWvlAL/UP3g9d18JM/BiIKJ1JbGNos=,tag:aYF//FyMDnxrKCrmSi+iGA==,type:str]
    DEMO_MESSAGE: ENC[AES256_GCM,data:jPRu4iJ0UWPgVxOn8o+9fdG/iYaPwRI=,iv:pPvphrMg8qn6TFvrk+hQNEQsoEKNOzV0MDG3p4SVlLw=,tag:TGggpAZ12UvEX8demJTg6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbGlGdUVQaGJCN1FVT2Ru
            OVpDTzhnNUpONjJIZ2REb1prN2ZCemNTc2tFCllITm4wckp6RkkzWlZvaE9QV3Vt
            cFk1ZFFQRzZSWUNNNUdWZDlHNEtVWVkKLS0tIEY2c0V2Y0NUSmoySEhrQlhvOFlm
            WUVVendMVkQwSUE2MHlNZC9ieWUwSTQKR2HtmJnyEztguNfCYyyZdx/+GGiGOfps
            E34hWvhe1aqqB06HKzsJt85e6D5sbf082P6eeLm0C2qFElwu+41cFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    lastmodified: "2026-09-30T11:37:29Z"
    mac: ENC[AES256_GCM,data:AZLcS32K4aVhWzo0kExKDjHnFcOU8x1s1xKH6eSUHdBlJBnO8WMzeQMHQAhjmPopwG7xt73s+WAP2g0KNBF7xPMG81DlzNaop+8D0t5V/R/shH+cYMOjA5KT8hvf71eGJUU78dAauAUfGMEE4EKd57wZ0DFpzNoYwQrErz296lU=,iv:aHgu1Y1bGFk8oSian1DOwEzN0JMA5N+hWaw7z28d5XQ=,tag:Er6/QR7Bs536kzC4sL9bAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
