apiVersion: ENC[AES256_GCM,data:By4=,iv:R8xZDDva6uXwypE+XDrRGYGaC+bCj1cchpBzNVuz2Xo=,tag:1FihGwcYqNiyCZQrkk+oTQ==,type:str]
kind: ENC[AES256_GCM,data:R19U05Ao,iv:pBD3+0AY2+nNeNGm/WajK7atDzTQyOlv714O/Mn8SGw=,tag:5qHeGlUeUzJi3gK29nypkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TUFV8CMSJTKY8ddIfw==,iv:3MvhMB7rTtfkGgCtxxq5c40mGgaqLJtN7+dOUK2iidk=,tag:7jA+hwSRJlk4rYHhV46I/A==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:Zo3AodSdcg==,iv:DaMWdK93thYyUdTERvbprt8Vn2/8soUblUJlR3JCYXI=,tag:nCE8p6IIbow285roXfsm/A==,type:str]
type: ENC[AES256_GCM,data:y+T75j4U,iv:xEw+fN+X0uEJqUOk+SRgJLXmYuY+DhLy08RSrNJlFHQ=,tag:jMWCs8Nhg9YD7Iq6IleRlA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:isDrpo8=,iv:BcPwMtxu+b8o9BiB8W+9gP+QVmxFbfHbUj/BHb0uZ2U=,tag:cgKVbENw5p/GQ1cXv180+A==,type:str]
    admin-password: ENC[AES256_GCM,data:TMqviJHAUqTOuRhI3McdT9Eu+jh3SIZ7AWyLe8lokXU=,iv:vdSts6cNdnWBLFOcWD21JmpCziMQlyndfZJ7YzLYrO4=,tag:q371+p1faeKsMK7uw5MbEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYXBOZEFVejFwbnRsR0NS
            MmRDa21kR2ltMTBsQXV6RXZXTDFtTnplZDJFCkJRdWNOSlplNlZISnpXai9XVTFt
            amRmZyt2SlZlblRuNlA3T25vUU9ONHcKLS0tIE05VlAxYytBN2x5YnU0Uzl6Tkx5
            QnQ2RDBCZDN4TVBzbC9Ra3FFS2ZaOWMKAgSRWVm9x4H+CjAKWrhpVAYshNz5tqqT
            MPBPu0aLiHVaWdzb0rh21hU4h5D2aqNa7QqEV/V1wPINdG9ObRkFvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13hphavvlee240rq0j42j60mqxj8s4k9tp473g076xl5z35p8mgjqx29stw
    lastmodified: "2026-09-30T16:55:21Z"
    mac: ENC[AES256_GCM,data:wHQbLHaJk1g892v8WtgibFj6bl+T5KanzC9cR2BnjEpGUSJ67kpz9dX8sFPceSLisU+UfxlL9Y2iNZSIwkpcxREhiG+BN9IY/yuZcAF1T1304fT6JSZSOi4eXlqdczzEWhx12Nb9b+L3tZOyIiSLVU/AgqPS/eMju4GBFwaSISM=,iv:sL/hiMudaUnKBmRFMzjSlYMcNefqFXyd3mFtTMbiHf0=,tag:Rjq9VV1U0j3TJIDPUcewRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
